# Generated by Django 4.1.1 on 2022-11-04 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='account',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='address',
            fields=[
                ('id_add', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('tinh_tp', models.CharField(max_length=20)),
                ('quan_huyen', models.CharField(max_length=20)),
                ('phuong_xa', models.CharField(max_length=20)),
                ('duong', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id_cmt', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('cmt', models.CharField(max_length=250)),
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='didii.account')),
            ],
        ),
        migrations.CreateModel(
            name='groupuser',
            fields=[
                ('id_gr', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('name_gr', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='interact',
            fields=[
                ('id_interact', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('love_count', models.IntegerField()),
                ('cmt_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='landlord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.DateField()),
                ('gender', models.BooleanField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=10)),
                ('numbranch', models.IntegerField()),
                ('vote', models.FloatField()),
                ('status', models.BooleanField()),
                ('id_add', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='didii.address')),
                ('id_gr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='didii.groupuser')),
                ('id_landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='didii.account')),
            ],
        ),
        migrations.CreateModel(
            name='post',
            fields=[
                ('id_post', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=250)),
                ('vote', models.FloatField()),
                ('cost', models.FloatField()),
                ('status', models.BooleanField()),
                ('id_add', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='didii.address')),
                ('id_cmt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='didii.comment')),
                ('id_interact_count', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='didii.interact')),
                ('id_landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='didii.landlord')),
            ],
        ),
        migrations.CreateModel(
            name='schedule',
            fields=[
                ('id_schedule', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('appointment_date', models.DateField()),
                ('booking_date', models.DateField()),
                ('id_cus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='didii.account')),
                ('id_landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='didii.landlord')),
                ('id_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='didii.post')),
            ],
        ),
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_cus', models.CharField(max_length=50)),
                ('age', models.DateField()),
                ('gender', models.BooleanField()),
                ('email', models.EmailField(max_length=250)),
                ('phone', models.CharField(max_length=10)),
                ('id_add', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='didii.address')),
                ('id_cus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='didii.account')),
                ('id_gr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='didii.groupuser')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='id_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='didii.post'),
        ),
        migrations.CreateModel(
            name='branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_add', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='didii.address')),
                ('id_landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='didii.landlord')),
            ],
        ),
    ]
