# Generated by Django 4.1.1 on 2022-11-22 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('didii', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='id_landlord',
        ),
        migrations.AddField(
            model_name='interact',
            name='id',
            field=models.BigAutoField(auto_created=True, default=2101, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='interact',
            name='id_interact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='didii.post', unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='id_interact_count',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='didii.interact', to_field='id_interact'),
        ),
        migrations.AlterField(
            model_name='post',
            name='id_post',
            field=models.AutoField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='didii.landlord'),
        ),
    ]
