# Generated by Django 4.1.1 on 2022-10-07 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('didii', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='House_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
            ],
        ),
    ]
