# Generated by Django 4.1.1 on 2022-10-10 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('didii', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='groupuesr',
            new_name='groupuser',
        ),
    ]
