# Generated by Django 4.1.1 on 2022-11-01 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('didii', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='id_branch',
        ),
        migrations.RemoveField(
            model_name='landlord',
            name='id_branch',
        ),
        migrations.AlterField(
            model_name='branch',
            name='id_landlord',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='didii.landlord'),
        ),
    ]
