# Generated by Django 4.1.1 on 2022-11-22 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('didii', '0002_remove_schedule_id_landlord_interact_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interact',
            name='id',
        ),
        migrations.RemoveField(
            model_name='post',
            name='id_interact_count',
        ),
        migrations.AddField(
            model_name='post',
            name='id_interact',
            field=models.ForeignKey(default=2101, on_delete=django.db.models.deletion.CASCADE, to='didii.interact'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='id_cmt',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='interact',
            name='id_interact',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='id_post',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
