# Generated by Django 4.1.1 on 2022-11-16 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('didii', '0002_post_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(default='', upload_to='images'),
        ),
    ]
