# Generated by Django 4.1.1 on 2022-12-03 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('didii', '0006_rename_duong_address_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id_landlord',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='didii.landlord'),
        ),
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
