# Generated by Django 4.1.1 on 2022-12-05 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('didii', '0007_alter_post_id_landlord_alter_post_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='email',
            new_name='email_ll',
        ),
        migrations.AddField(
            model_name='schedule',
            name='email_cus',
            field=models.ForeignKey(default=2101, on_delete=django.db.models.deletion.CASCADE, to='didii.customer'),
            preserve_default=False,
        ),
    ]
